baseURL = "https://iboneumann.github.io/The-Cyberdeck---AI-Knoweldge-System/"
#baseURL = "http://localhost:1313"
canonifyURLs = true
languageCode = "en-us"
title = "The Cyberdeck - AI Knowledge System"
theme = "hugo-dead-simple"

[params]
  description = "Research on AI Computing and RAG systems"
  author = "ibo neumann"
  centerTitle = true

[taxonomies]
  tag = "tags"

# Menu configuration (if your theme supports it)
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 2
